version: "3.9"
services:
  web:
    image: restaurant:latest
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "npm run build && npm start"

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"

  # Uncomment this later when you add PostgreSQL:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: