name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: AWS Credential configures
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: AWS ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and push docker img to ECR
        run: |
          IMAGE_URI=${{secrets.ECR_REPOSITORY}}:latest
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t $IMAGE_URI --push .

      - name: Verify Docker image platform
        run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY }}:latest
          docker buildx imagetools inspect $IMAGE_URI | grep "Architecture"

      - name: Create .env.production file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.production
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.production
          echo "DEV_ADMIN_SECRET=${{ secrets.DEV_ADMIN_SECRET }}" >> .env.production
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env.production
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env.production
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.production
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env.production

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            scp -o StrictHostKeyChecking=no .env.production ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/.env.production
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
              docker pull ${{ secrets.ECR_REPOSITORY }}:latest &&
              docker stop restaurant || true &&
              docker rm restaurant || true &&
              docker run -d --restart unless-stopped --env-file /home/${{ secrets.EC2_USER }}/.env.production --name restaurant -p 80:3000 ${{ secrets.ECR_REPOSITORY }}:latest
            "